//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.25 at 02:52:31 PM MSK 
//


package org.example.monitoring.canonical;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for templateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="templateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sysObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="metrics">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="cpuLoad" type="{http://www.example.org/zbx_template_new/}metricType"/>
 *                   &lt;element name="cpuUtil" type="{http://www.example.org/zbx_template_new/}metricType" minOccurs="0"/>
 *                   &lt;element name="memoryUsed" type="{http://www.example.org/zbx_template_new/}metricType"/>
 *                   &lt;element name="memoryFree" type="{http://www.example.org/zbx_template_new/}metricType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "templateType", propOrder = {

})
public class TemplateType {

    @XmlElement(required = true)
    protected String name;
    protected String description;
    @XmlElement(required = true)
    protected String sysObjectID;
    @XmlElement(required = true)
    protected TemplateType.Metrics metrics;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the sysObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSysObjectID() {
        return sysObjectID;
    }

    /**
     * Sets the value of the sysObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSysObjectID(String value) {
        this.sysObjectID = value;
    }

    /**
     * Gets the value of the metrics property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateType.Metrics }
     *     
     */
    public TemplateType.Metrics getMetrics() {
        return metrics;
    }

    /**
     * Sets the value of the metrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateType.Metrics }
     *     
     */
    public void setMetrics(TemplateType.Metrics value) {
        this.metrics = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="cpuLoad" type="{http://www.example.org/zbx_template_new/}metricType"/>
     *         &lt;element name="cpuUtil" type="{http://www.example.org/zbx_template_new/}metricType" minOccurs="0"/>
     *         &lt;element name="memoryUsed" type="{http://www.example.org/zbx_template_new/}metricType"/>
     *         &lt;element name="memoryFree" type="{http://www.example.org/zbx_template_new/}metricType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Metrics {

        @XmlElement(required = true)
        protected MetricType cpuLoad;
        protected MetricType cpuUtil;
        @XmlElement(required = true)
        protected MetricType memoryUsed;
        @XmlElement(required = true)
        protected MetricType memoryFree;

        /**
         * Gets the value of the cpuLoad property.
         * 
         * @return
         *     possible object is
         *     {@link MetricType }
         *     
         */
        public MetricType getCpuLoad() {
            return cpuLoad;
        }

        /**
         * Sets the value of the cpuLoad property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetricType }
         *     
         */
        public void setCpuLoad(MetricType value) {
            this.cpuLoad = value;
        }

        /**
         * Gets the value of the cpuUtil property.
         * 
         * @return
         *     possible object is
         *     {@link MetricType }
         *     
         */
        public MetricType getCpuUtil() {
            return cpuUtil;
        }

        /**
         * Sets the value of the cpuUtil property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetricType }
         *     
         */
        public void setCpuUtil(MetricType value) {
            this.cpuUtil = value;
        }

        /**
         * Gets the value of the memoryUsed property.
         * 
         * @return
         *     possible object is
         *     {@link MetricType }
         *     
         */
        public MetricType getMemoryUsed() {
            return memoryUsed;
        }

        /**
         * Sets the value of the memoryUsed property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetricType }
         *     
         */
        public void setMemoryUsed(MetricType value) {
            this.memoryUsed = value;
        }

        /**
         * Gets the value of the memoryFree property.
         * 
         * @return
         *     possible object is
         *     {@link MetricType }
         *     
         */
        public MetricType getMemoryFree() {
            return memoryFree;
        }

        /**
         * Sets the value of the memoryFree property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetricType }
         *     
         */
        public void setMemoryFree(MetricType value) {
            this.memoryFree = value;
        }

    }

}
