//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.25 at 02:10:37 PM MSK 
//


package org.example.monitoring.zabbix_template;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.monitoring.zabbix_template package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototypeValuemapName_QNAME = new QName("", "name");
    private final static QName _ZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleTriggerPrototypesTriggerPrototypeDependenciesDependency_QNAME = new QName("", "dependency");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.monitoring.zabbix_template
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZabbixExport }
     * 
     */
    public ZabbixExport createZabbixExport() {
        return new ZabbixExport();
    }

    /**
     * Create an instance of {@link ZabbixExport.ValueMaps }
     * 
     */
    public ZabbixExport.ValueMaps createZabbixExportValueMaps() {
        return new ZabbixExport.ValueMaps();
    }

    /**
     * Create an instance of {@link ZabbixExport.ValueMaps.ValueMap }
     * 
     */
    public ZabbixExport.ValueMaps.ValueMap createZabbixExportValueMapsValueMap() {
        return new ZabbixExport.ValueMaps.ValueMap();
    }

    /**
     * Create an instance of {@link ZabbixExport.ValueMaps.ValueMap.Mappings }
     * 
     */
    public ZabbixExport.ValueMaps.ValueMap.Mappings createZabbixExportValueMapsValueMapMappings() {
        return new ZabbixExport.ValueMaps.ValueMap.Mappings();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates }
     * 
     */
    public ZabbixExport.Templates createZabbixExportTemplates() {
        return new ZabbixExport.Templates();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template }
     * 
     */
    public ZabbixExport.Templates.Template createZabbixExportTemplatesTemplate() {
        return new ZabbixExport.Templates.Template();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Screens }
     * 
     */
    public ZabbixExport.Templates.Template.Screens createZabbixExportTemplatesTemplateScreens() {
        return new ZabbixExport.Templates.Template.Screens();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Screens.Screen }
     * 
     */
    public ZabbixExport.Templates.Template.Screens.Screen createZabbixExportTemplatesTemplateScreensScreen() {
        return new ZabbixExport.Templates.Template.Screens.Screen();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Screens.Screen.ScreenItems }
     * 
     */
    public ZabbixExport.Templates.Template.Screens.Screen.ScreenItems createZabbixExportTemplatesTemplateScreensScreenScreenItems() {
        return new ZabbixExport.Templates.Template.Screens.Screen.ScreenItems();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Screens.Screen.ScreenItems.ScreenItem }
     * 
     */
    public ZabbixExport.Templates.Template.Screens.Screen.ScreenItems.ScreenItem createZabbixExportTemplatesTemplateScreensScreenScreenItemsScreenItem() {
        return new ZabbixExport.Templates.Template.Screens.Screen.ScreenItems.ScreenItem();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Macros }
     * 
     */
    public ZabbixExport.Templates.Template.Macros createZabbixExportTemplatesTemplateMacros() {
        return new ZabbixExport.Templates.Template.Macros();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules createZabbixExportTemplatesTemplateDiscoveryRules() {
        return new ZabbixExport.Templates.Template.DiscoveryRules();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRule() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleGraphPrototypes() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleGraphPrototypesGraphPrototype() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleGraphPrototypesGraphPrototypeGraphItems() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems.GraphItem }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems.GraphItem createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleGraphPrototypesGraphPrototypeGraphItemsGraphItem() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems.GraphItem();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleTriggerPrototypes() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleTriggerPrototypesTriggerPrototype() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleTriggerPrototypesTriggerPrototypeDependencies() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypes() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototype() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.ApplicationPrototypes }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.ApplicationPrototypes createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototypeApplicationPrototypes() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.ApplicationPrototypes();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Applications }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Applications createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototypeApplications() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Applications();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleFilter() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter.Conditions }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter.Conditions createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleFilterConditions() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter.Conditions();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Items }
     * 
     */
    public ZabbixExport.Templates.Template.Items createZabbixExportTemplatesTemplateItems() {
        return new ZabbixExport.Templates.Template.Items();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Applications }
     * 
     */
    public ZabbixExport.Templates.Template.Applications createZabbixExportTemplatesTemplateApplications() {
        return new ZabbixExport.Templates.Template.Applications();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Groups }
     * 
     */
    public ZabbixExport.Templates.Template.Groups createZabbixExportTemplatesTemplateGroups() {
        return new ZabbixExport.Templates.Template.Groups();
    }

    /**
     * Create an instance of {@link ZabbixExport.Groups }
     * 
     */
    public ZabbixExport.Groups createZabbixExportGroups() {
        return new ZabbixExport.Groups();
    }

    /**
     * Create an instance of {@link ZabbixExport.ValueMaps.ValueMap.Mappings.Mapping }
     * 
     */
    public ZabbixExport.ValueMaps.ValueMap.Mappings.Mapping createZabbixExportValueMapsValueMapMappingsMapping() {
        return new ZabbixExport.ValueMaps.ValueMap.Mappings.Mapping();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Screens.Screen.ScreenItems.ScreenItem.Resource }
     * 
     */
    public ZabbixExport.Templates.Template.Screens.Screen.ScreenItems.ScreenItem.Resource createZabbixExportTemplatesTemplateScreensScreenScreenItemsScreenItemResource() {
        return new ZabbixExport.Templates.Template.Screens.Screen.ScreenItems.ScreenItem.Resource();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Macros.Macro }
     * 
     */
    public ZabbixExport.Templates.Template.Macros.Macro createZabbixExportTemplatesTemplateMacrosMacro() {
        return new ZabbixExport.Templates.Template.Macros.Macro();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems.GraphItem.Item }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems.GraphItem.Item createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleGraphPrototypesGraphPrototypeGraphItemsGraphItemItem() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.GraphPrototypes.GraphPrototype.GraphItems.GraphItem.Item();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.Dependency }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.Dependency createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleTriggerPrototypesTriggerPrototypeDependenciesDependency() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.Dependency();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Valuemap }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Valuemap createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototypeValuemap() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Valuemap();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.ApplicationPrototypes.ApplicationPrototype }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.ApplicationPrototypes.ApplicationPrototype createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototypeApplicationPrototypesApplicationPrototype() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.ApplicationPrototypes.ApplicationPrototype();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Applications.Application }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Applications.Application createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototypeApplicationsApplication() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Applications.Application();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter.Conditions.Condition }
     * 
     */
    public ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter.Conditions.Condition createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleFilterConditionsCondition() {
        return new ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.Filter.Conditions.Condition();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Items.Item }
     * 
     */
    public ZabbixExport.Templates.Template.Items.Item createZabbixExportTemplatesTemplateItemsItem() {
        return new ZabbixExport.Templates.Template.Items.Item();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Applications.Application }
     * 
     */
    public ZabbixExport.Templates.Template.Applications.Application createZabbixExportTemplatesTemplateApplicationsApplication() {
        return new ZabbixExport.Templates.Template.Applications.Application();
    }

    /**
     * Create an instance of {@link ZabbixExport.Templates.Template.Groups.Group }
     * 
     */
    public ZabbixExport.Templates.Template.Groups.Group createZabbixExportTemplatesTemplateGroupsGroup() {
        return new ZabbixExport.Templates.Template.Groups.Group();
    }

    /**
     * Create an instance of {@link ZabbixExport.Groups.Group }
     * 
     */
    public ZabbixExport.Groups.Group createZabbixExportGroupsGroup() {
        return new ZabbixExport.Groups.Group();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name", scope = ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Valuemap.class)
    public JAXBElement<String> createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototypeValuemapName(String value) {
        return new JAXBElement<String>(_ZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleItemPrototypesItemPrototypeValuemapName_QNAME, String.class, ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.ItemPrototypes.ItemPrototype.Valuemap.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.Dependency }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dependency", scope = ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.class)
    public JAXBElement<ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.Dependency> createZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleTriggerPrototypesTriggerPrototypeDependenciesDependency(ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.Dependency value) {
        return new JAXBElement<ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.Dependency>(_ZabbixExportTemplatesTemplateDiscoveryRulesDiscoveryRuleTriggerPrototypesTriggerPrototypeDependenciesDependency_QNAME, ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.Dependency.class, ZabbixExport.Templates.Template.DiscoveryRules.DiscoveryRule.TriggerPrototypes.TriggerPrototype.Dependencies.class, value);
    }

}
