package org.zabbix.template.generator.objects
global org.slf4j.Logger logger;

//replaces TEMPLATE_NAME:METRIC name
rule "Rule: generate each trigger expression"
	agenda-group "populate"
	no-loop
when
    
    $m : Metric ($key: key != null, $triggers: triggers)
    $t : Template(metricsRegistry contains $m)
    $tr: Trigger ($e: expression!=null) from $triggers 
then
    logger.info("Generating trigger expression (changing TEMPLATE_NAME:METRIC) for "+ $tr);
    $tr.setExpression( $e.replaceAll("TEMPLATE_NAME:METRIC",$t.getName()+":"+$key));
end



//replaces TEMPLATE_NAME:METRIC name
rule "Rule: generate each trigger recovery expression"
	agenda-group "populate"
	no-loop
when
    
    $m : Metric ($key: key != null, $triggers: triggers)
    $t : Template(metricsRegistry contains $m)
    $tr: Trigger ($e: recoveryExpression!=null) from $triggers 
then
    logger.info("Generating trigger recoverExpression (changing TEMPLATE_NAME:METRIC) for "+ $tr);
    $tr.setExpression( $e.replaceAll("TEMPLATE_NAME:METRIC",$t.getName()+":"+$key));
end
