package org.zabbix.template.generator.objects
global org.slf4j.Logger logger;

/*
This will found trigger pairs (inside single metric ONLY(fix?)). If there is a trigger mentioned in dependsOn - add it to dependsOn
For example. This doesn' catch ICMP ping dependencies inside ICMP ping template
*/

rule "Generate each trigger dependency"
	agenda-group "populate.trigger.dependencies"
	no-loop
when
	$m : Metric ($triggers: triggers)
	$tr: Trigger ($dependsOn: dependsOn) from $triggers
	
	$m2 : Metric ($triggers2: triggers, $m.discoveryRule == discoveryRule)
    $tr2: Trigger ($dependsOn contains id) from $triggers2 
then
    logger.info("Found dependency "+$tr2.getId()+" for "+ $tr.getName());
    $tr.getDependencies().add(new TriggerDependency($tr2.getName(), $tr2.getExpression(), $tr2.getRecoveryExpression()));
end