package org.zabbix.template.generator.objects
global org.slf4j.Logger logger;


rule "Rule 12a: generate each trigger description"
	agenda-group "populate"
	no-loop
when
    $m : Metric ($triggers: triggers)
    $tr: Trigger (description==null) from $triggers 
then
    logger.debug("Generating trigger description for "+ $tr);
    $tr.setDescription( "Last value: {ITEM.LASTVALUE1}.");
end

rule "Rule 12b: generate each trigger description"
	agenda-group "populate"
	no-loop
when
	$m : Metric ($triggers: triggers)
    $tr: Trigger (description!=null) from $triggers 
then
    logger.debug("Generating trigger description for "+ $tr);
    $tr.setDescription( "Last value: {ITEM.LASTVALUE1}.\n"+$tr.getDescription() );
end