package org.zabbix.template.generator.objects
global org.slf4j.Logger logger;


rule "Validation rule 1: you should have both discoveryRule and alarmObject defined"
	agenda-group "validate"
when
	$m : Metric (discoveryRule != null, alarmObject == null )
then
    logger.error("Please define 'alarmObject' for "+$m);
end


rule "Validation rule 2: check key"
	agenda-group "validate"
when
	$m : Metric (key == null)
then
    logger.error("There is no 'key' for "+$m.getName());
end


rule "Validation rule: check name"
	agenda-group "validate"
when
	$m : Metric (name == null)
then
    logger.error("There is no 'name' for "+$m);
end

/* TODO 
rule "Validation rule 3: valueMap mentioned in metric should be defined"
	agenda-group "validate"
when
	$m: Metric($vm_name : valueMap != null)
	$t : InputJSON()
	ValueMap ( name != $vm_name) from $t.valueMaps 	
then
    logger.info("Found value map for "+ $vm_name);
end
*/