package drl
import com.company.license.Applicant;
import org.zabbix.template.generator.objects.Metric;

rule "Check oid"
when
      $m : Metric (  snmpObject != null, oid != null )
then
    System.err.println("Check oid rule!");
    $m.setKey("Changed key");
end


rule "Is of valid age"
when
      $a : Applicant(  age < 18 )
then
    System.out.println("Not valid!");
    $a.setValid( true );
end

/*
rule "Hello World"
when
    Applicant( name == "Mr John Smith" )
then
    System.out.println( "Hello Chuck" );
end

rule "Hello World2"
when 
   eval(true)
then
    System.out.println("Hello world");
end*/